SELECT w.worker_tabnumber tab_num,
       INITCAP(RTRIM(w.worker_familyname)) family,
       INITCAP(RTRIM(w.worker_firstname)) name,
       INITCAP(RTRIM(w.worker_surname)) surname,
       case when w.worker_sex = 0 then 'М'
            when w.worker_sex = 1 then 'Ж'
       end sex,  
       --coalesce(COMPANY.COMPANY_ID, company1.company_id, company2.company_id) COMPANY_ID, 
       --swg1.subjectwg_id DEPART_ID, -- для связки с НС2000
       RTRIM(nvl(nvl(nvl(nvl(company3.company_fullname, company1.company_fullname), company.company_fullname), company2.company_fullname), company4.company_fullname)) COMPANY,
       RTRIM(upper(swg1.subjectwg_longname)) DEPARTMENT,        
       RTRIM(upper(wp.wposition_fullname)) POSITION,
       COMPANY.COMPANY_ID COMPANY_ID,
       WTT.WTRANSIT_DATE
             
FROM SYSDBA.T_WORKER W
JOIN SYSDBA.STAFFWORKER SW ON W.WORKER_ID = SW.WORKER_ID 
  AND (sw.stafftype_id = 1 or sw.stafftype_id = 3)
  AND (SW.STAFFWORKER_DATEEND > SYSDATE OR sw.staffworker_dateend IS NULL)
JOIN SYSDBA.STAFF S ON SW.SUBJECTWG_ID = S.SUBJECTWG_ID
LEFT JOIN SYSDBA.WPOSITION WP ON s.wposition_id = wp.wposition_id 
JOIN SYSDBA.T_SUBJECTWG SWG ON swg.SUBJECTWG_ID = S.SUBJECTWG_ID
JOIN SYSDBA.SUBWORKGROUP sub ON sub.WORKGROUP_ID = SWG.WORKGROUP_ID
JOIN SYSDBA.T_SUBJECTWG SWG1 ON swg1.SUBJECTWG_ID = sub.SUBJECTWG_ID
LEFT JOIN SYSDBA.WORKGROUPCOMPANY WGC3 ON swg1.SUBJECTWG_ID = wgc3.SUBJECTWG_ID
LEFT JOIN SYSDBA.COMPANY COMPANY3 ON WGC3.COMPANY_ID = COMPANY3.COMPANY_ID
LEFT JOIN SYSDBA.SUBWORKGROUP sub1 ON sub1.WORKGROUP_ID = SWG1.WORKGROUP_ID
LEFT JOIN SYSDBA.T_SUBJECTWG SWG2 ON swg2.SUBJECTWG_ID = sub1.SUBJECTWG_ID
LEFT JOIN SYSDBA.WORKGROUPCOMPANY WGC1 ON swg2.SUBJECTWG_ID = wgc1.SUBJECTWG_ID
LEFT JOIN SYSDBA.COMPANY COMPANY1 ON WGC1.COMPANY_ID = COMPANY1.COMPANY_ID
LEFT JOIN SYSDBA.SUBWORKGROUP sub2 ON sub2.WORKGROUP_ID = SWG2.WORKGROUP_ID
LEFT JOIN SYSDBA.T_SUBJECTWG SWG3 ON swg3.SUBJECTWG_ID = sub2.SUBJECTWG_ID
LEFT JOIN SYSDBA.WORKGROUPCOMPANY WGC ON swg3.SUBJECTWG_ID = wgc.SUBJECTWG_ID
LEFT JOIN SYSDBA.COMPANY COMPANY ON WGC.COMPANY_ID = COMPANY.COMPANY_ID
LEFT JOIN SYSDBA.SUBWORKGROUP sub3 ON sub3.WORKGROUP_ID = SWG3.WORKGROUP_ID
LEFT JOIN SYSDBA.T_SUBJECTWG SWG4 ON swg4.SUBJECTWG_ID = sub3.SUBJECTWG_ID
LEFT JOIN SYSDBA.WORKGROUPCOMPANY WGC2 ON swg4.SUBJECTWG_ID = wgc2.SUBJECTWG_ID
LEFT JOIN SYSDBA.COMPANY COMPANY2 ON WGC2.COMPANY_ID = COMPANY2.COMPANY_ID
LEFT JOIN SYSDBA.SUBWORKGROUP sub4 ON sub4.WORKGROUP_ID = swg4.WORKGROUP_ID
LEFT JOIN SYSDBA.T_SUBJECTWG SWG5 ON swg5.SUBJECTWG_ID = sub4.SUBJECTWG_ID
LEFT JOIN SYSDBA.WORKGROUPCOMPANY WGC4 ON swg5.SUBJECTWG_ID = wgc4.SUBJECTWG_ID
LEFT JOIN SYSDBA.COMPANY COMPANY4 ON WGC4.COMPANY_ID = COMPANY4.COMPANY_ID
LEFT JOIN SYSDBA.wtransit WTT ON W.WORKER_ID = WTT.WORKER_ID
  AND (WTT.wtransittype_id = 12)
  AND (WTT.WTRANSIT_DATE is NULL)
ORDER BY TO_CHAR(w.worker_birthday, 'DD.MM'), w.worker_familyname
